use Debian Bullseye for linuxfr-board docker image
`linuxfr-board` has a dependency which requires now at least Ruby 2.5.0:

```
Step 7/10 : RUN gem install board-linuxfr -v '~> 0.1.3'
 ---> Running in 47eba4572c41
ERROR:  Error installing board-linuxfr:
        einhorn requires Ruby version >= 2.5.0.
Successfully installed multi_json-1.15.0
Successfully installed rack-1.6.13
Successfully installed async-rack-0.5.0
Successfully installed rack-accept-media-types-0.9
Successfully installed rack-respond_to-0.9.8
Successfully installed rack-contrib-1.8.0
The command '/bin/sh -c gem install board-linuxfr -v '~> 0.1.3'' returned a non-zero code: 1
ERROR: Service 'linuxfr-board' failed to build : Build failed
```